### ISSUE TITLE
Prevent refresh on second+ page of view

### ISSUE THREAD

**Issue by wbhob** [brandonstubbs/ZendeskRefresh#2]
Looks like the extension pulls you back to the first page on reload. I can help PR, but we want to see if there's a way to prevent reload if not on the first page, as in those circumstances you're probably not needing the results to refresh since they're older.

**Comment by brandonstubbs** [comment]
Hi,

Sorry for the delay in response I did not see this. Which page are you referring to? It would probably be possible to detect if a user has moved to another page for paginated results

**Comment by wbhob** [comment]
I am not actually with that company any more, so I no longer use Zendesk. But as I recall, the issue was that on the "Tickets" or "Views" page, if you navigate further into the pagination, you get thrown back to the first page on autorefresh.

**Comment by brandonstubbs** [comment]
Thank you for the hint area as I too haven't been with a company that uses Zendesk in some time and a fresh copy of Zendesk you have to create over 30 tickets to even get the pagination (So definitely not clear)😉

There wasn't a clean way to work out if the user is on another page that I could. However, there is an obfuscated CSS to change the mouse to a pointer to click on other pages, so put some logic in on that.
