### ISSUE TITLE
Zendesk update

### ISSUE THREAD

**Issue by miachan96** [brandonstubbs/ZendeskRefresh#3]
My Zendesk has an update yesterday and now, the View is unable to automatically refreshed (however, this app still works for Dashboard).

Could you please help?

**Comment by brandonstubbs** [comment]
Hi, thanks for reaching out. There must have been an update to either Chrome / Zendesk. I will work on a fix

**Comment by brandonstubbs** [comment]
I have submitted a new version to the Chrome store. As soon as their verification process has complete you will receive the latest update.
